### ISSUE TITLE
Offline access issue

### ISSUE THREAD

**Issue by amitmerchant1990** [hemanth/jsfeatures.in#109]
For some reason jsfeatures.in taking longer than usual when loading it offline in mobile. It got stuck at splash screen for over 1 min. I have checked it on Android Marshmallow. 

The site however loads ultimately but after significant delay.

**Comment by hemanth** [comment]
Thanks for reporting, we shall look into it.

**Comment by gokulkrishh** [comment]
@amitmerchant1990 Can you let us know the browser and version of it. Thanks

**Comment by amitmerchant1990** [comment]
@gokulkrishh It's the latest version of Chrome on Android.

**Comment by gokulkrishh** [comment]
@amitmerchant1990 Thanks!!
