### ISSUE TITLE
link is not working 

### ISSUE THREAD

**Issue by jitendra3109** [hemanth/jsfeatures.in#116]
Please update this link +> https://jsfeatures.in/

**Comment by hemanth** [comment]
Yeah noticed, held up with other things, you have time to investigate this?

**Comment by jitendra3109** [comment]
sure! I would do that.
In the primary not getting an error.
The domain is valid.

Domain ID:D9583080-AFIN
Domain Name:JSFEATURES.IN
Created On:22-Jun-2015 13:30:10 UTC
Last Updated On:22-Jun-2017 18:05:56 UTC
Expiration Date:22-Jun-2018 13:30:10 UTC
Sponsoring Registrar:Endurance Domains Technology LLP (R173-AFIN)

Wouldn't mind adding collaboration?

**Comment by hemanth** [comment]
Done

**Comment by ar5had** [comment]
can't open jsfeatures.in :(

**Comment by jitendra3109** [comment]
The issue with Cloudflare security, also needs to check on the setting of repo.

**Comment by hemanth** [comment]
@jsroyal cloudflare says it's all green, what's the issue you are seeing?

**Comment by hemanth** [comment]
It's back.
