### ISSUE TITLE
Block scope example, should be *let* not *const*

### ISSUE THREAD

**Issue by jthomas** [hemanth/jsfeatures.in#20]
<pre>
var aboutme = () => {
  {
    var investements = 1;
    const salary = 10;
  }
  console.log(investements, salary); // 1, undefined.
}
</pre>

to

<pre>
var aboutme = () => {
  {
    var investements = 1;
    let salary = 10;
  }
  console.log(investements, salary); // 1, undefined.
}
</pre>

**Comment by hemanth** [comment]
Specific reason?

**Comment by jthomas** [comment]
Looking back at this now, I've misunderstood the code! Sorry.

**Comment by hemanth** [comment]
NP :+1:
